# Timeout in seconds that Limine will use before automatically booting.
TIMEOUT=5

# The entry name that will be displayed in the boot menu.
:ComputeKERNEL (Limine)

# The protocol to use.
PROTOCOL=limine

# Path to the kernel to boot. boot:/// represents the partition the loader was loaded from.
KERNEL_PATH=boot:///boot/computekernel.elf

# Set resolution for the interface and preferred for the kernel.
# Limine will try 800x600 first. On real hardware, if it fails, it will pick the best available.
INTERFACE_RESOLUTION=800x600
