ARCH    ?= x86_64
PROFILE ?= debug

OUT   := out
BUILD := build

CC      := gcc
AS      := gcc
LD      := ld

# ── Base compiler flags ──────────────────────────────────────────────
CFLAGS_BASE := -ffreestanding -fno-builtin -fno-stack-protector \
               -mno-red-zone -mno-mmx -mno-sse -mno-sse2 \
               -m64 -std=c11 -Iinclude -Wall -Wextra \
               -fno-pic -fno-pie -mcmodel=kernel

# ── Profile-specific flags ───────────────────────────────────────────
ifeq ($(PROFILE),release)
    CFLAGS_PROFILE := -O2 -DNDEBUG
else
    CFLAGS_PROFILE := -g -O0 -DDEBUG
endif

CFLAGS  := $(CFLAGS_BASE) $(CFLAGS_PROFILE)

# Generate dependency files alongside object files
DEPFLAGS = -MMD -MP

ASFLAGS := -m64 -c -Iinclude

LDFLAGS := -T arch/x86_64/linker.ld -nostdlib -z max-page-size=0x1000

SRCS_C  := \
    kernel/init/main.c \
    kernel/printk.c \
    kernel/stubs.c \
    kernel/lib/string.c \
    kernel/drivers/serial.c \
    kernel/drivers/font.c \
    kernel/arch/x86_64/gdt.c \
    kernel/arch/x86_64/idt.c \
    kernel/arch/x86_64/pic.c \
    kernel/arch/x86_64/pit.c \
    kernel/arch/x86_64/keyboard.c \
    kernel/arch/x86_64/mouse.c \
    kernel/arch/x86_64/cpu.c \
    kernel/arch/x86_64/syscall.c \
    kernel/mm/pmm.c \
    kernel/mm/heap.c \
    kernel/net/stack.c \
    kernel/net/nic.c \
    kernel/net/sshd.c \
    kernel/sched/sched.c \
    kernel/vfs/vfs.c \
    kernel/vfs/ramfs.c \
    kernel/shell/shell.c

SRCS_S  := boot/x86_64/entry64.S \
           boot/x86_64/isr_stubs.S \
           boot/x86_64/switch.S \
           boot/x86_64/syscall_entry.S

OBJS    := $(patsubst %.S, $(BUILD)/%.o, $(SRCS_S)) \
           $(patsubst %.c, $(BUILD)/%.o, $(SRCS_C))

# Dependency files (auto-generated by -MMD)
DEPS    := $(patsubst %.c, $(BUILD)/%.d, $(SRCS_C))

KERNEL  := $(OUT)/computekernel.elf

.PHONY: all help kernel iso img run qemu kvm vmware vbox gdb test lint rust-check size-report clean

all: kernel

help:
	@echo "ComputeKERNEL build targets:"
	@echo "  make kernel           - compile kernel ELF (PROFILE=debug|release)"
	@echo "  make iso              - build bootable ISO (requires Limine + xorriso)"
	@echo "  make img              - build bootable .img (requires root + loop device)"
	@echo "  make run|qemu         - run with QEMU"
	@echo "  make kvm              - run with QEMU+KVM accel"
	@echo "  make vmware           - print VMware instructions"
	@echo "  make vbox             - print VirtualBox instructions"
	@echo "  make gdb              - print gdb attach instructions"
	@echo "  make test             - run tooling checks"
	@echo "  make lint             - shell/python syntax checks"
	@echo "  make rust-check       - run Rust check if rust crate exists"
	@echo "  make size-report      - report kernel binary size"
	@echo "  make clean            - remove build artefacts"
	@echo ""
	@echo "  PROFILE=release make kernel   - optimised build (-O2)"
	@echo "  PROFILE=debug   make kernel   - debug build (-g -O0, default)"

kernel: $(KERNEL)

$(KERNEL): $(OBJS)
	@mkdir -p $(OUT)
	$(LD) $(LDFLAGS) -o $@ $^
	@echo "[CK] kernel → $@  ($(shell wc -c < $@ 2>/dev/null || echo '?') bytes)"

# C sources: compile with dependency tracking
$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEPFLAGS) -MF $(patsubst %.o,%.d,$@) -c -o $@ $<

# Assembly sources
$(BUILD)/%.o: %.S
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) -o $@ $<

# Include auto-generated dependency files (silently ignore if missing)
-include $(DEPS)

iso: kernel
	@./scripts/build-iso.sh

img: kernel
	@./scripts/build-img.sh

run: qemu

qemu:
	@./scripts/run-qemu.sh

kvm:
	@./scripts/run-kvm.sh

vmware:
	@./scripts/run-vmware.sh

vbox:
	@./scripts/run-vbox.sh

gdb:
	@./scripts/debug-gdb.sh

test:
	@./scripts/test.sh

lint:
	@sh -n scripts/*.sh
	@python3 -m py_compile tools/*.py
	@echo "lint checks passed"

rust-check:
	@if [ -f rust/Cargo.toml ]; then \
		if command -v cargo >/dev/null 2>&1; then \
			cd rust && \
			if command -v rustup >/dev/null 2>&1 && \
			   rustup target list --installed | grep -q '^x86_64-unknown-none$$'; then \
				cargo check --target x86_64-unknown-none; \
			else \
				echo "x86_64-unknown-none target not installed; running host cargo check"; \
				cargo check; \
			fi; \
		else \
			echo "cargo not found; skipping rust-check"; \
		fi; \
	else \
		echo "rust/Cargo.toml not present yet; skipping rust-check"; \
	fi

size-report:
	@if [ -f $(KERNEL) ]; then \
		echo "Kernel ELF: $$(wc -c < $(KERNEL)) bytes"; \
		command -v size >/dev/null 2>&1 && size $(KERNEL) || true; \
	else \
		echo "$(KERNEL) does not exist yet – run 'make kernel' first"; \
	fi
	@du -sh $(OUT) 2>/dev/null || true

clean:
	rm -rf $(BUILD) $(OUT)
	@echo "[CK] build artefacts removed"
