#!/usr/bin/env python3
"""Generate a simple syscall number header for early ComputeKERNEL scaffolding."""

from __future__ import annotations

import argparse
from pathlib import Path

SYSCALLS = [
    "read",
    "write",
    "openat",
    "close",
    "exit",
    "fork",
    "execve",
    "wait4",
    "mmap",
    "munmap",
    "brk",
    "nanosleep",
    "getpid",
    "kill",
]


def write_syscall_header(output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "syscall_nr.h"
    with path.open("w", encoding="utf-8") as f:
        f.write("/* Generated by tools/gen_syscalls.py */\n")
        for idx, name in enumerate(SYSCALLS):
            f.write(f"#define __NR_{name} {idx}\n")
    return path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="Output directory")
    args = parser.parse_args()

    generated_path = write_syscall_header(Path(args.out))
    print(f"generated: {generated_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
